version: 0.0.0.{build}

clone_depth: 1

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS-BigSur

before_build:
  - 'git submodule update --init --recursive'

build_script:
  - sh: './SDL-ios.sh'
  - sh: './SDL-tvos.sh'
  - sh: './archive.sh'

after_build:
  - sh: appveyor PushArtifact moonlight-ios-deps.zip

deploy: off
