version: 0.0.0.{build}

clone_depth: 1

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS-Sonoma
      OS_MIN: 12.0
      OPUS_VERSION: 1.5.2
      BUILD_TARGET: apple
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
      BUILD_TARGET: android
      NDK_VER: 27.0.12077973

before_build:
  - 'git submodule update --init --recursive'
  - sh: '[ "$BUILD_TARGET" != apple ] || curl -LO "https://downloads.xiph.org/releases/opus/opus-$OPUS_VERSION.tar.gz"'
  - sh: '[ "$BUILD_TARGET" != android ] || which sdkmanager'
  - sh: '[ "$BUILD_TARGET" != android ] || sdkmanager --install "ndk;$NDK_VER"'
  - sh: '[ "$BUILD_TARGET" != android ] || export NDK=/usr/lib/android-sdk/ndk/$NDK_VER'
  - sh: 'mkdir build'

build_script:
  - sh: '[ "$BUILD_TARGET" != apple ] || ./build-apple.sh'
  - sh: '[ "$BUILD_TARGET" != android ] || ./build-android.sh'
  - sh: '[ "$BUILD_TARGET" != apple ] || ./archive-apple.sh'
  - sh: '[ "$BUILD_TARGET" != android ] || ./archive-android.sh'

after_build:
  - sh: '[ "$BUILD_TARGET" != apple ] || appveyor PushArtifact moonlight-apple-deps.zip'
  - sh: '[ "$BUILD_TARGET" != android ] || appveyor PushArtifact moonlight-android-deps.zip'

deploy: off
